services:
    - type: web
      name: innovaplay-backend
      env: python
      plan: free
      buildCommand: ""
      startCommand: gunicorn run:app
      envVars:
          - key: SELF_URL
            value: https://innovaplay-backend.onrender.com
