# -*- coding: utf-8 -*-
"""Valores de recompensa de Jogos e Play TV. Única fonte — sem mágicos espalhados."""

CONTENT_TYPE_GAME = "game"
CONTENT_TYPE_VIDEO = "video"

REASON_GAME_PLAY = "game_play"
REASON_PLAYTV_WATCH = "playtv_watch"

GAME_REWARD_COINS = 10
VIDEO_REWARD_COINS = 15

DAILY_CAP_COINS = 50
DAILY_CAP_TIMEZONE = "America/Sao_Paulo"

GAME_MIN_VISIBLE_SECONDS = 60
VIDEO_FALLBACK_SECONDS = 120

YOUTUBE_WATCHED_PERCENT = 80
YOUTUBE_MIN_WALL_SECONDS = 30
YOUTUBE_DURATION_FACTOR = 0.4

ACHIEVEMENT_EXPLORADOR_JOGOS = "explorador_jogos"
ACHIEVEMENT_MARATONISTA_PLAY_TV = "maratonista_play_tv"

CONTENT_ACHIEVEMENT_IDS = frozenset({
    ACHIEVEMENT_EXPLORADOR_JOGOS,
    ACHIEVEMENT_MARATONISTA_PLAY_TV,
})
