/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedResultadosRouteImport } from './routes/_authenticated/resultados'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlunoRouteImport } from './routes/_authenticated/aluno'
import { Route as AuthenticatedQuestoesIndexRouteImport } from './routes/_authenticated/questoes.index'
import { Route as AuthenticatedQuestoesNovaRouteImport } from './routes/_authenticated/questoes.nova'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedResultadosRoute = AuthenticatedResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlunoRoute = AuthenticatedAlunoRouteImport.update({
  id: '/aluno',
  path: '/aluno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestoesIndexRoute =
  AuthenticatedQuestoesIndexRouteImport.update({
    id: '/questoes/',
    path: '/questoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestoesNovaRoute =
  AuthenticatedQuestoesNovaRouteImport.update({
    id: '/questoes/nova',
    path: '/questoes/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aluno': typeof AuthenticatedAlunoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/questoes/nova': typeof AuthenticatedQuestoesNovaRoute
  '/questoes/': typeof AuthenticatedQuestoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aluno': typeof AuthenticatedAlunoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/resultados': typeof AuthenticatedResultadosRoute
  '/questoes/nova': typeof AuthenticatedQuestoesNovaRoute
  '/questoes': typeof AuthenticatedQuestoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/aluno': typeof AuthenticatedAlunoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/resultados': typeof AuthenticatedResultadosRoute
  '/_authenticated/questoes/nova': typeof AuthenticatedQuestoesNovaRoute
  '/_authenticated/questoes/': typeof AuthenticatedQuestoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aluno'
    | '/dashboard'
    | '/resultados'
    | '/questoes/nova'
    | '/questoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aluno'
    | '/dashboard'
    | '/resultados'
    | '/questoes/nova'
    | '/questoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/aluno'
    | '/_authenticated/dashboard'
    | '/_authenticated/resultados'
    | '/_authenticated/questoes/nova'
    | '/_authenticated/questoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/resultados': {
      id: '/_authenticated/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof AuthenticatedResultadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aluno': {
      id: '/_authenticated/aluno'
      path: '/aluno'
      fullPath: '/aluno'
      preLoaderRoute: typeof AuthenticatedAlunoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questoes/': {
      id: '/_authenticated/questoes/'
      path: '/questoes'
      fullPath: '/questoes/'
      preLoaderRoute: typeof AuthenticatedQuestoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questoes/nova': {
      id: '/_authenticated/questoes/nova'
      path: '/questoes/nova'
      fullPath: '/questoes/nova'
      preLoaderRoute: typeof AuthenticatedQuestoesNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlunoRoute: typeof AuthenticatedAlunoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedResultadosRoute: typeof AuthenticatedResultadosRoute
  AuthenticatedQuestoesNovaRoute: typeof AuthenticatedQuestoesNovaRoute
  AuthenticatedQuestoesIndexRoute: typeof AuthenticatedQuestoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlunoRoute: AuthenticatedAlunoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedResultadosRoute: AuthenticatedResultadosRoute,
  AuthenticatedQuestoesNovaRoute: AuthenticatedQuestoesNovaRoute,
  AuthenticatedQuestoesIndexRoute: AuthenticatedQuestoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
