"""added binary fields to physical_test_forms

Revision ID: 0fe0422f58b0
Revises: 79caf408ad15
Create Date: 2025-09-05 13:52:59.293765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe0422f58b0'
down_revision = '79caf408ad15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_test_forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_pdf_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('answer_sheet_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('correction_image_data', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_test_forms', schema=None) as batch_op:
        batch_op.drop_column('correction_image_data')
        batch_op.drop_column('answer_sheet_data')
        batch_op.drop_column('form_pdf_data')

    # ### end Alembic commands ###
