"""Fix expected_tasks to be nullable and add batch_id

Revision ID: 20260203_fix_expected_tasks
Revises: c5eac53e27b6
Create Date: 2026-02-03 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260203_fix_expected_tasks'
down_revision = 'c5eac53e27b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Tornar expected_tasks NULLABLE se existir
    # Usar batch mode para SQLite/PostgreSQL compatibilidade
    with op.batch_alter_table('answer_sheet_gabaritos', schema=None) as batch_op:
        # Tentar tornar nullable - se a coluna não existir, não vai dar erro
        try:
            batch_op.alter_column('expected_tasks',
                                existing_type=sa.Integer(),
                                nullable=True)
        except:
            pass  # Se coluna não existir, ignora
    
    # 2. Adicionar campo batch_id para agrupar gabaritos gerados juntos
    with op.batch_alter_table('answer_sheet_gabaritos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(36), nullable=True))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remover batch_id
    with op.batch_alter_table('answer_sheet_gabaritos', schema=None) as batch_op:
        batch_op.drop_column('batch_id')
    
    # Tornar expected_tasks NOT NULL novamente (se necessário)
    # Deixar como estava antes
    
    # ### end Alembic commands ###
