"""add_num_questions_to_form_coordinates

Revision ID: 266a3a4f7474
Revises: b813cdb16b4d
Create Date: 2025-09-18 17:20:09.939783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266a3a4f7474'
down_revision = 'b813cdb16b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_coordinates', sa.Column('num_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('form_coordinates', 'num_questions')
    # ### end Alembic commands ###
