"""add_actual_start_time_to_test_sessions

Revision ID: 289cf9ee1f00
Revises: 6d9936ac7b77
Create Date: 2025-07-12 03:03:46.022681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '289cf9ee1f00'
down_revision = '6d9936ac7b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar campo actual_start_time e tornar started_at nullable
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_start_time', sa.DateTime(), nullable=True))
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover campo actual_start_time e tornar started_at obrigatório novamente
    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('actual_start_time')
    # ### end Alembic commands ###
