"""add student_password_log and cleanup school_course indexes

Revision ID: 2f8318725482
Revises: 39bcc7ca5bcb
Create Date: 2025-11-04 15:06:17.783314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f8318725482'
down_revision = '39bcc7ca5bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_password_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('registration', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('city_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grade.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_course_education_stage_id'))
        batch_op.drop_index(batch_op.f('ix_school_course_school_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_course_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_course_education_stage_id'), ['education_stage_id'], unique=False)

    op.drop_table('student_password_log')
    # ### end Alembic commands ###
