"""add_user_relationship_to_student

Revision ID: 6d9936ac7b77
Revises: 48b50f609011
Create Date: 2025-07-12 02:09:39.351834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d9936ac7b77'
down_revision = '48b50f609011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_correct', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_column('is_correct')

    # ### end Alembic commands ###
