"""add physical test models

Revision ID: 79caf408ad15
Revises: b576007eadf8
Create Date: 2025-09-05 13:20:14.912645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79caf408ad15'
down_revision = 'b576007eadf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_test_forms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('class_test_id', sa.String(), nullable=False),
    sa.Column('form_pdf_url', sa.String(), nullable=True),
    sa.Column('answer_sheet_url', sa.String(), nullable=True),
    sa.Column('correction_image_url', sa.String(), nullable=True),
    sa.Column('qr_code_data', sa.String(), nullable=False),
    sa.Column('qr_code_coordinates', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_corrected', sa.Boolean(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_test_id'], ['class_test.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physical_test_answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('physical_form_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('marked_answer', sa.String(), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('detection_coordinates', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['physical_form_id'], ['physical_test_forms.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physical_test_answers')
    op.drop_table('physical_test_forms')
    # ### end Alembic commands ###
