"""Add school_course table for linking courses to schools

Revision ID: add_school_course
Revises: add_batch_correction_job
Create Date: 2024-01-20 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_school_course'
down_revision = 'c30630f8e10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_course',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('school_id', sa.String(), nullable=False),
    sa.Column('education_stage_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['education_stage_id'], ['education_stage.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'education_stage_id', name='uq_school_education_stage')
    )
    op.create_index(op.f('ix_school_course_school_id'), 'school_course', ['school_id'], unique=False)
    op.create_index(op.f('ix_school_course_education_stage_id'), 'school_course', ['education_stage_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_school_course_education_stage_id'), table_name='school_course')
    op.drop_index(op.f('ix_school_course_school_id'), table_name='school_course')
    op.drop_table('school_course')
    # ### end Alembic commands ###

