"""Add BatchCorrectionJob model for batch physical test correction

Revision ID: add_batch_correction_job
Revises: 0fe0422f58b0
Create Date: 2024-01-20 10:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_batch_correction_job'
down_revision = '266a3a4f7474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_correction_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_images', sa.Integer(), nullable=False),
    sa.Column('processed_images', sa.Integer(), nullable=False),
    sa.Column('successful_corrections', sa.Integer(), nullable=False),
    sa.Column('failed_corrections', sa.Integer(), nullable=False),
    sa.Column('current_student_id', sa.String(length=36), nullable=True),
    sa.Column('current_student_name', sa.String(length=255), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('images_data', sa.Text(), nullable=True),
    sa.Column('gabarito_data', sa.Text(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_completion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_correction_jobs')
    # ### end Alembic commands ###
