"""test_after_cleanup

Revision ID: b576007eadf8
Revises: b823c1deebf2
Create Date: 2025-09-05 13:05:00.349426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b576007eadf8'
down_revision = 'b823c1deebf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('teacher_school')
    with op.batch_alter_table('class_test', schema=None) as batch_op:
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               comment='Timezone da aplicação da avaliação (ex: America/Sao_Paulo)',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'])

    with op.batch_alter_table('education_stage', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('education_stages_name_key'), type_='unique')

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('grades_education_stage_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'education_stage', ['education_stage_id'], ['id'])

    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='ID único do manager (UUID)',
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nome completo do manager',
               existing_nullable=False)
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='URL da foto de perfil',
               existing_nullable=True)
        batch_op.alter_column('registration',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Matrícula única do manager',
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Data de nascimento',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Referência para a tabela users',
               existing_nullable=True)
        batch_op.alter_column('school_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Escola vinculada (para diretores e coordenadores)',
               existing_nullable=True)
        batch_op.alter_column('city_id',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Cidade vinculada (para tecadm)',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_manager_city_id'))
        batch_op.drop_index(batch_op.f('idx_manager_registration'))
        batch_op.drop_index(batch_op.f('idx_manager_school_id'))
        batch_op.drop_index(batch_op.f('idx_manager_user_id'))
        batch_op.drop_table_comment(
        existing_comment='Tabela para armazenar informações de diretores, coordenadores e tecadm'
    )

    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_test_questions_order'))
        batch_op.drop_index(batch_op.f('idx_test_questions_question_id'))
        batch_op.drop_index(batch_op.f('idx_test_questions_test_id'))
        batch_op.drop_constraint(batch_op.f('test_questions_test_id_question_id_key'), type_='unique')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'])
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'])

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.alter_column('actual_start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Horário real de início da sessão de prova',
               existing_nullable=True)
        batch_op.alter_column('manual_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Pontuação manual atribuída pelo professor',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_test_sessions_actual_start_time'))
        batch_op.drop_index(batch_op.f('idx_test_sessions_started_at'))
        batch_op.drop_index(batch_op.f('idx_test_sessions_status'))
        batch_op.drop_index(batch_op.f('idx_test_sessions_student_test'))
        batch_op.drop_index(batch_op.f('idx_test_sessions_submitted_at'))
        batch_op.drop_constraint(batch_op.f('fk_test_sessions_corrected_by_users'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'])
        batch_op.drop_table_comment(
        existing_comment='Tabela de sessões de teste - Frontend responsável pelo cronômetro'
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('reset_token',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Token único para redefinição de senha',
               existing_nullable=True)
        batch_op.alter_column('reset_token_expires',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Data e hora de expiração do token de reset',
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_users_reset_token'))
        batch_op.drop_index(batch_op.f('idx_users_reset_token_expires'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_reset_token_expires'), ['reset_token_expires'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_reset_token'), ['reset_token'], unique=False)
        batch_op.alter_column('reset_token_expires',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data e hora de expiração do token de reset',
               existing_nullable=True)
        batch_op.alter_column('reset_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Token único para redefinição de senha',
               existing_nullable=True)

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tabela de sessões de teste - Frontend responsável pelo cronômetro',
        existing_comment=None
    )
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_test_sessions_corrected_by_users'), 'users', ['corrected_by'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_test_sessions_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_sessions_student_test'), ['student_id', 'test_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_sessions_actual_start_time'), ['actual_start_time'], unique=False)
        batch_op.alter_column('manual_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Pontuação manual atribuída pelo professor',
               existing_nullable=True)
        batch_op.alter_column('actual_start_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Horário real de início da sessão de prova',
               existing_nullable=True)

    with op.batch_alter_table('test_questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint(batch_op.f('test_questions_test_id_question_id_key'), ['test_id', 'question_id'])
        batch_op.create_index(batch_op.f('idx_test_questions_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_questions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_test_questions_order'), ['order'], unique=False)

    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.create_table_comment(
        'Tabela para armazenar informações de diretores, coordenadores e tecadm',
        existing_comment=None
    )
        batch_op.create_index(batch_op.f('idx_manager_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_manager_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_manager_registration'), ['registration'], unique=False)
        batch_op.create_index(batch_op.f('idx_manager_city_id'), ['city_id'], unique=False)
        batch_op.alter_column('city_id',
               existing_type=sa.VARCHAR(),
               comment='Cidade vinculada (para tecadm)',
               existing_nullable=True)
        batch_op.alter_column('school_id',
               existing_type=sa.VARCHAR(),
               comment='Escola vinculada (para diretores e coordenadores)',
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(),
               comment='Referência para a tabela users',
               existing_nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               comment='Data de nascimento',
               existing_nullable=True)
        batch_op.alter_column('registration',
               existing_type=sa.VARCHAR(length=50),
               comment='Matrícula única do manager',
               existing_nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(),
               comment='URL da foto de perfil',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nome completo do manager',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(),
               comment='ID único do manager (UUID)',
               existing_nullable=False)

    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('grades_education_stage_id_fkey'), 'education_stage', ['education_stage_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('education_stage', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('education_stages_name_key'), ['name'])

    with op.batch_alter_table('class_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('timezone',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Timezone da aplicação da avaliação (ex: America/Sao_Paulo)',
               existing_nullable=True)

    op.create_table('teacher_school',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('teacher_school_school_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('teacher_school_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teacher_school_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('ALUNO', 'PROFESSOR', 'COORDENADOR', 'DIRETOR', 'ADMIN', 'tecadm', 'TECADM', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['city.id'], name=op.f('user_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'))
    )
    # ### end Alembic commands ###
