"""initial Migration

Revision ID: b823c1deebf2
Revises: 
Create Date: 2025-07-06 15:06:49.079691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'b823c1deebf2'
down_revision = None
branch_labels = None
depends_on = None


def _table_exists(inspector, table_name, schema=None):
    return inspector.has_table(table_name, schema=schema)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('user')
    # op.drop_table('teacher_school')  # Comentado para evitar erro de timeout
    
    # Verificar se as colunas existem antes de adicionar
    conn = op.get_bind()
    inspector = inspect(conn)
    
    # Verificar colunas da tabela class_subject (só se a tabela existir)
    if _table_exists(inspector, 'class_subject'):
        class_subject_columns = [c['name'] for c in inspector.get_columns('class_subject')]
        with op.batch_alter_table('class_subject', schema=None) as batch_op:
            if 'created_at' not in class_subject_columns:
                batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
            if 'updated_at' not in class_subject_columns:
                batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    if _table_exists(inspector, 'class_test'):
        with op.batch_alter_table('class_test', schema=None) as batch_op:
            # Verificar se a foreign key já existe antes de criar
            try:
                batch_op.create_foreign_key(None, 'test', ['test_id'], ['id'])
            except Exception:
                pass  # Foreign key já existe

    # with op.batch_alter_table('education_stage', schema=None) as batch_op:  # Comentado para evitar timeout
    #     batch_op.alter_column('id',
    #            existing_type=sa.UUID(),
    #            type_=sa.String(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('gen_random_uuid()'))
    #     batch_op.alter_column('name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    #     batch_op.drop_constraint(batch_op.f('education_stages_name_key'), type_='unique')

    # with op.batch_alter_table('grade', schema=None) as batch_op:  # Comentado para evitar timeout
    #     batch_op.alter_column('name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    #     batch_op.alter_column('education_stage_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    #     batch_op.drop_constraint(batch_op.f('grades_education_stage_id_fkey'), type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'education_stage', ['education_stage_id'], ['id'])

    if _table_exists(inspector, 'skills'):
        with op.batch_alter_table('skills', schema=None) as batch_op:
            batch_op.alter_column('code',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=False)
            batch_op.alter_column('description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=False)
            batch_op.alter_column('subject_id',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)

    # Verificar colunas da tabela student_answers
    if _table_exists(inspector, 'student_answers'):
        student_answers_columns = [c['name'] for c in inspector.get_columns('student_answers')]
        with op.batch_alter_table('student_answers', schema=None) as batch_op:
            if 'manual_score' not in student_answers_columns:
                batch_op.add_column(sa.Column('manual_score', sa.Float(), nullable=True))
            if 'feedback' not in student_answers_columns:
                batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
            if 'corrected_by' not in student_answers_columns:
                batch_op.add_column(sa.Column('corrected_by', sa.String(), nullable=True))
            if 'corrected_at' not in student_answers_columns:
                batch_op.add_column(sa.Column('corrected_at', sa.DateTime(), nullable=True))
            # Verificar se a foreign key já existe antes de criar
            try:
                batch_op.create_foreign_key(None, 'users', ['corrected_by'], ['id'])
            except Exception:
                pass  # Foreign key já existe

    # Verificar índices da tabela test antes de remover
    if _table_exists(inspector, 'test'):
        test_indexes = [idx['name'] for idx in inspector.get_indexes('test')]
        with op.batch_alter_table('test', schema=None) as batch_op:
            batch_op.alter_column('end_time',
                   existing_type=postgresql.TIMESTAMP(),
                   comment=None,
                   existing_comment='Data e hora de término da disponibilidade da avaliação',
                   existing_nullable=True)
            batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True,
                   comment=None,
                   existing_comment='Status da avaliação: agendada, em_andamento, concluida, cancelada',
                   existing_server_default=sa.text("'agendada'::character varying"))
            # Verificar se o índice existe antes de remover
            if 'idx_test_end_time' in test_indexes:
                batch_op.drop_index(batch_op.f('idx_test_end_time'))

    # Verificar colunas da tabela test_sessions
    if _table_exists(inspector, 'test_sessions'):
        test_sessions_columns = [c['name'] for c in inspector.get_columns('test_sessions')]
        with op.batch_alter_table('test_sessions', schema=None) as batch_op:
            if 'feedback' not in test_sessions_columns:
                batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))
            if 'corrected_by' not in test_sessions_columns:
                batch_op.add_column(sa.Column('corrected_by', sa.String(), nullable=True))
            if 'corrected_at' not in test_sessions_columns:
                batch_op.add_column(sa.Column('corrected_at', sa.DateTime(), nullable=True))
            # Verificar se a foreign key já existe antes de criar
            try:
                batch_op.create_foreign_key(None, 'users', ['corrected_by'], ['id'])
            except Exception:
                pass  # Foreign key já existe

    # Verificar índices da tabela users antes de remover
    if _table_exists(inspector, 'users'):
        users_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('reset_token',
                   existing_type=sa.VARCHAR(length=255),
                   comment=None,
                   existing_comment='Token único para redefinição de senha',
                   existing_nullable=True)
            batch_op.alter_column('reset_token_expires',
                   existing_type=postgresql.TIMESTAMP(),
                   comment=None,
                   existing_comment='Data e hora de expiração do token de reset',
                   existing_nullable=True)
            # Verificar se os índices existem antes de remover
            if 'idx_users_reset_token' in users_indexes:
                batch_op.drop_index(batch_op.f('idx_users_reset_token'))
            if 'idx_users_reset_token_expires' in users_indexes:
                batch_op.drop_index(batch_op.f('idx_users_reset_token_expires'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_users_reset_token_expires'), ['reset_token_expires'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_reset_token'), ['reset_token'], unique=False)
        batch_op.alter_column('reset_token_expires',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data e hora de expiração do token de reset',
               existing_nullable=True)
        batch_op.alter_column('reset_token',
               existing_type=sa.VARCHAR(length=255),
               comment='Token único para redefinição de senha',
               existing_nullable=True)

    with op.batch_alter_table('test_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('corrected_at')
        batch_op.drop_column('corrected_by')
        batch_op.drop_column('feedback')

    with op.batch_alter_table('test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_test_end_time'), ['end_time'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='Status da avaliação: agendada, em_andamento, concluida, cancelada',
               existing_server_default=sa.text("'agendada'::character varying"))
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Data e hora de término da disponibilidade da avaliação',
               existing_nullable=True)

    with op.batch_alter_table('student_answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('corrected_at')
        batch_op.drop_column('corrected_by')
        batch_op.drop_column('feedback')
        batch_op.drop_column('manual_score')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.alter_column('subject_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # with op.batch_alter_table('grade', schema=None) as batch_op:  # Comentado para evitar timeout
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(batch_op.f('grades_education_stage_id_fkey'), 'education_stage', ['education_stage_id'], ['id'], ondelete='CASCADE')
    #     batch_op.alter_column('education_stage_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    #     batch_op.alter_column('name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)

    # with op.batch_alter_table('education_stage', schema=None) as batch_op:  # Comentado para evitar timeout
    #     batch_op.create_unique_constraint(batch_op.f('education_stages_name_key'), ['name'])
    #     batch_op.alter_column('name',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    #     batch_op.alter_column('id',
    #            existing_type=sa.String(),
    #            type_=sa.UUID(),
    #            existing_nullable=False,
    #            existing_server_default=sa.text('gen_random_uuid()'))

    with op.batch_alter_table('class_test', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('class_subject', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # op.create_table('teacher_school',  # Comentado para evitar erro de timeout
    # sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('teacher_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('school_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['school_id'], ['school.id'], name=op.f('teacher_school_school_id_fkey')),
    # sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('teacher_school_teacher_id_fkey')),
    # sa.PrimaryKeyConstraint('id', name=op.f('teacher_school_pkey'))
    # )
    op.create_table('user',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('ALUNO', 'PROFESSOR', 'COORDENADOR', 'DIRETOR', 'ADMIN', 'tecadm', 'TECADM', name='roleenum'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['city.id'], name=op.f('user_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('email', name=op.f('user_email_key'))
    )
    # ### end Alembic commands ###
