"""calendar: create events, targets, event_users

Revision ID: c30630f8e10a
Revises: 6e291f89aa03
Create Date: 2025-10-30 17:34:19.940532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30630f8e10a'
down_revision = '6e291f89aa03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('start_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('recurrence_rule', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_by_role', sa.String(length=32), nullable=False),
    sa.Column('visibility_scope', sa.Enum('SCHOOL_ALL', 'MUNICIPALITY', 'SCHOOL', 'GRADE', 'CLASS', 'USERS', name='calendarvisibilityscope'), nullable=False),
    sa.Column('municipality_id', sa.String(), nullable=True),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['city.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_event_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('target_type', sa.Enum('MUNICIPALITY', 'SCHOOL', 'GRADE', 'CLASS', 'USER', name='calendartargettype'), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_event_users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('school_id', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('role_snapshot', sa.String(length=32), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['calendar_events.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['school.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_correction_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_batch_correction_jobs_created_at'))
        batch_op.drop_index(batch_op.f('idx_batch_correction_jobs_created_by'))
        batch_op.drop_index(batch_op.f('idx_batch_correction_jobs_status'))
        batch_op.drop_index(batch_op.f('idx_batch_correction_jobs_test_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('batch_correction_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_batch_correction_jobs_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_correction_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_correction_jobs_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('idx_batch_correction_jobs_created_at'), ['created_at'], unique=False)

    op.drop_table('calendar_event_users')
    op.drop_table('calendar_event_targets')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
