"""Add answer_sheet_gabaritos table

Revision ID: ccd58942d465
Revises: 882088fd9c7a
Create Date: 2025-12-05 18:18:38.812019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ccd58942d465'
down_revision = '882088fd9c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_sheet_gabaritos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('test_id', sa.String(), nullable=True),
    sa.Column('class_id', sa.String(), nullable=True),
    sa.Column('num_questions', sa.Integer(), nullable=False),
    sa.Column('use_blocks', sa.Boolean(), nullable=True),
    sa.Column('blocks_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_settings_user_id'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_settings_user_id'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    op.drop_table('answer_sheet_gabaritos')
    # ### end Alembic commands ###
