from .municipio import Municipio
from .professor import Professor
from .escola import Escola
from .avaliacao import Avaliacao
from .educationStage import EducationStage
from .grades import Grade
from .turmas import Turma
from .aluno import Aluno
from .usuario import Usuario
