from .city import City
from .school import School
from .schoolTeacher import SchoolTeacher
from .teacher import Teacher
from .student import Student
from .subject import Subject
from .studentClass import Class
from .classSubject import ClassSubject
from .classTest import ClassTest
from .test import Test
from .testQuestion import TestQuestion
from .educationStage import EducationStage
from .grades import Grade
from .skill import Skill
from .question import Question
from .studentAnswer import StudentAnswer
from .testSession import TestSession
from .userQuickLinks import UserQuickLinks
from .teacherClass import TeacherClass
from .user import User
from .game import Game
from .evaluationResult import EvaluationResult
from .manager import Manager
from .physicalTestAnswer import PhysicalTestAnswer
from .physicalTestForm import PhysicalTestForm
from .formCoordinates import FormCoordinates

