name: Backend Pipeline

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix:
                server: [vps-afirme, vps-limoeiro]
        runs-on: 
            - self-hosted
            - ${{ matrix.server }}
        environment: prod
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Deploy
              run: |
                  export COMPOSE_PROJECT_NAME=afirmeplay_back_prod # Isso faz com que o docker compose separe os containers de produção dos de desenvolvimento
                  export VERSION=v$(cat VERSION)
                  export DATABASE_URL=${{ secrets.DATABASE_URL }}
                  # Enable Scheduler
                  export ENABLE_SCHEDULER=${{ secrets.ENABLE_SCHEDULER }}
                  # JWT Secret Key
                  export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
                  # Frontend
                  export FRONTEND_URL=${{ secrets.FRONTEND_URL}}
                  # SendGrid
                  export SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
                  export SENDGRID_FROM_EMAIL=${{ secrets.SENDGRID_FROM_EMAIL }}
                  # Telegram
                  export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
                  export TELEGRAM_GROUP_ID=${{ secrets.TELEGRAM_GROUP_ID }}
                  export TELEGRAM_ALERT_ENABLED=${{ secrets.TELEGRAM_ALERT_ENABLED }}
                  # Celery & Redis
                  export CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
                  export CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }}
                  export REDIS_URL=${{ secrets.REDIS_URL }}
                  export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
                  # MinIO
                  export MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}
                  export MINIO_SERVER_URL=${{ secrets.MINIO_SERVER_URL }}
                  export MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}
                  export MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}
                  export MINIO_SECURE=${{ secrets.MINIO_SECURE }}
                  export MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}
                  export MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}
                  # Google AI Studio
                  export GOOGLE_AI_STUDIO_API_KEY=${{ secrets.GOOGLE_AI_STUDIO_API_KEY }}
                  export GOOGLE_AI_STUDIO_MODEL=${{ secrets.GOOGLE_AI_STUDIO_MODEL }}
                  # App Environment
                  export APP_ENV=${{ secrets.APP_ENV }}
                  export PUBLIC_API_BASE_URL=${{ secrets.PUBLIC_API_BASE_URL }}
                  export SUBDOMAIN_MODE=${{ secrets.SUBDOMAIN_MODE }}

                  docker compose -f docker-compose.prod.yml pull
                  docker compose -f docker-compose.prod.yml up -d
