name: Backend Pipeline

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, vps-artur]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build Images
        run: |
            docker build -t afirmeplay/afirmeplay-backend:v${{env.VERSION}} .
            docker built -t afirmeplay/afirmeplay-backend:latest .
  push:
    runs-on: [self-hosted, vps-artur]
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
            password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Get Version
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Push Images
        run: |
          docker push afirmeplay/afirmeplay-backend:v${{ env.VERSION }}
          docker push afirmeplay/afirmeplay-backend:latest

  deploy:
    runs-on: [self-hosted, vps-artur]
    needs: [push]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: |
            export COMPOSE_PROJECT_NAME=afirmeplay_back_dev # Isso faz com que o docker compose separe os containers de produção dos de desenvolvimento
            export VERSION=v$(cat VERSION)
            export DATABASE_URL=${{ secrets.DATABASE_URL }}
            export FRONTEND_URL=${{ secrets.FRONTEND_URL}}

            docker compose -f docker-compose.dev.yml pull
            docker compose -f docker-compose.dev.yml up -d
        
                  
            
