name: Backend Pipeline

on:
    push:
        branches:
            - dev
    workflow_dispatch:

jobs:
    build:
        runs-on: [self-hosted, vps-afirme]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Get Version
              run: |
                  VERSION=$(cat VERSION)
                  echo "VERSION=${VERSION}" >> $GITHUB_ENV

            - name: Build Images
              run: |
                  docker build -t afirmeplay/afirmeplay-backend:v${{env.VERSION}} .
                  docker build -t afirmeplay/afirmeplay-backend:latest .
    push:
        runs-on: [self-hosted, vps-artur]
        needs: [build]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
            - name: Get Version
              run: |
                  VERSION=$(cat VERSION)
                  echo "VERSION=${VERSION}" >> $GITHUB_ENV
            - name: Push Images
              run: |
                  docker push afirmeplay/afirmeplay-backend:v${{ env.VERSION }}
                  docker push afirmeplay/afirmeplay-backend:latest

    deploy:
        runs-on: [self-hosted, vps-artur]
        environment: dev
        needs: [push]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Deploy
              run: |
                  export COMPOSE_PROJECT_NAME=afirmeplay_back_dev # Isso faz com que o docker compose separe os containers de produção dos de desenvolvimento
                  export VERSION=v$(cat VERSION)
                  export DATABASE_URL=${{ secrets.DATABASE_URL }}
                  # JWT Secret Key
                  export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
                  # Frontend
                  export FRONTEND_URL=${{ secrets.FRONTEND_URL}}
                  # SendGrid
                  export SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
                  export SENDGRID_FROM_EMAIL=${{ secrets.SENDGRID_FROM_EMAIL }}
                  # Telegram
                  export TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
                  export TELEGRAM_GROUP_ID=${{ secrets.TELEGRAM_GROUP_ID }}
                  export TELEGRAM_ALERT_ENABLED=${{ secrets.TELEGRAM_ALERT_ENABLED }}
                  # Celery & Redis
                  export CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}
                  export CELERY_RESULT_BACKEND=${{ secrets.CELERY_RESULT_BACKEND }}
                  export REDIS_URL=${{ secrets.REDIS_URL }}
                  export REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
                  # MinIO
                  export MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}
                  export MINIO_SERVER_URL=${{ secrets.MINIO_SERVER_URL }}
                  export MINIO_ROOT_USER=${{ secrets.MINIO_ROOT_USER }}
                  export MINIO_ROOT_PASSWORD=${{ secrets.MINIO_ROOT_PASSWORD }}
                  export MINIO_SECURE=${{ secrets.MINIO_SECURE }}]
                  export MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}
                  export MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}
                  # Google AI Studio
                  export GOOGLE_AI_STUDIO_API_KEY=${{ secrets.GOOGLE_AI_STUDIO_API_KEY }}
                  export GOOGLE_AI_STUDIO_MODEL=${{ secrets.GOOGLE_AI_STUDIO_MODEL }}
                  # App Environment
                  export APP_ENV=${{ secrets.APP_ENV }}
                  export PUBLIC_API_BASE_URL=${{ secrets.PUBLIC_API_BASE_URL }}
                  export SUBDOMAIN_MODE=${{ secrets.SUBDOMAIN_MODE }}

                  docker compose -f docker-compose.dev.yml pull
                  docker compose -f docker-compose.dev.yml up -d
